-- Bank accounts table for storing connected bank accounts
CREATE TABLE public.bank_accounts (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  account_name TEXT NOT NULL,
  account_number_masked TEXT, -- Last 4 digits only for security
  institution_name TEXT NOT NULL,
  institution_logo_url TEXT,
  account_type TEXT NOT NULL DEFAULT 'checking', -- checking, savings, credit, loan
  currency TEXT NOT NULL DEFAULT 'USD',
  current_balance DECIMAL(15,2),
  available_balance DECIMAL(15,2),
  connection_provider TEXT, -- 'plaid', 'truelayer', 'basiq', 'manual'
  connection_id TEXT, -- External provider connection ID
  access_token_encrypted TEXT,
  last_sync_at TIMESTAMP WITH TIME ZONE,
  sync_status TEXT DEFAULT 'pending', -- pending, syncing, synced, error
  sync_error TEXT,
  is_primary BOOLEAN DEFAULT false,
  is_active BOOLEAN DEFAULT true,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Bank transactions table for imported/synced transactions
CREATE TABLE public.bank_transactions (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  bank_account_id UUID NOT NULL REFERENCES public.bank_accounts(id) ON DELETE CASCADE,
  external_id TEXT, -- ID from bank/provider for deduplication
  transaction_date DATE NOT NULL,
  posted_date DATE,
  description TEXT NOT NULL,
  merchant_name TEXT,
  merchant_category TEXT,
  amount DECIMAL(15,2) NOT NULL,
  currency TEXT NOT NULL DEFAULT 'USD',
  transaction_type TEXT NOT NULL, -- debit, credit
  category TEXT,
  is_pending BOOLEAN DEFAULT false,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  UNIQUE(bank_account_id, external_id)
);

-- Transaction reconciliation table - links bank transactions to financial records
CREATE TABLE public.transaction_reconciliations (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  bank_transaction_id UUID NOT NULL REFERENCES public.bank_transactions(id) ON DELETE CASCADE,
  financial_record_id UUID REFERENCES public.csuite_financials(id) ON DELETE SET NULL,
  match_type TEXT NOT NULL, -- 'auto', 'manual', 'suggested', 'split'
  match_confidence DECIMAL(5,2), -- 0-100 confidence score for auto-matches
  match_status TEXT NOT NULL DEFAULT 'pending', -- pending, confirmed, rejected, split
  matched_by TEXT, -- 'atlas_ai', 'user', 'rule'
  match_notes TEXT,
  split_details JSONB, -- For transactions split across multiple records
  reviewed_at TIMESTAMP WITH TIME ZONE,
  reviewed_by UUID,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Tax configurations per region
CREATE TABLE public.tax_configurations (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  country_code TEXT NOT NULL, -- ISO 3166-1 alpha-2
  country_name TEXT NOT NULL,
  tax_type TEXT NOT NULL, -- 'gst', 'vat', 'sales_tax', 'income_tax'
  tax_name TEXT NOT NULL, -- 'GST', 'VAT', 'Sales Tax', etc.
  standard_rate DECIMAL(5,2) NOT NULL, -- Percentage
  reduced_rates JSONB, -- Array of reduced rates with conditions
  threshold_amount DECIMAL(15,2), -- Registration threshold
  threshold_currency TEXT DEFAULT 'USD',
  filing_frequency TEXT, -- 'monthly', 'quarterly', 'annually'
  tax_year_start TEXT, -- 'jan', 'apr', 'jul', 'oct'
  rules JSONB, -- Additional rules and exemptions
  is_active BOOLEAN DEFAULT true,
  effective_from DATE NOT NULL,
  effective_to DATE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- User tax settings
CREATE TABLE public.user_tax_settings (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  primary_country_code TEXT NOT NULL,
  tax_registration_number TEXT, -- ABN, VAT number, EIN, etc.
  is_registered_for_tax BOOLEAN DEFAULT false,
  registration_date DATE,
  filing_frequency TEXT,
  accounting_method TEXT DEFAULT 'accrual', -- 'cash', 'accrual'
  tax_year_end_month INTEGER DEFAULT 12, -- 1-12
  auto_calculate_tax BOOLEAN DEFAULT true,
  include_tax_in_prices BOOLEAN DEFAULT false,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  UNIQUE(user_id)
);

-- Financial insights generated by Atlas AI
CREATE TABLE public.financial_insights (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  insight_type TEXT NOT NULL, -- 'cashflow_forecast', 'spending_alert', 'tax_reminder', 'optimization', 'anomaly'
  priority TEXT NOT NULL DEFAULT 'medium', -- 'low', 'medium', 'high', 'critical'
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  recommendation TEXT,
  impact_amount DECIMAL(15,2),
  impact_currency TEXT DEFAULT 'USD',
  related_entity_type TEXT, -- 'transaction', 'invoice', 'bill', 'account'
  related_entity_id UUID,
  data JSONB, -- Supporting data for the insight
  is_read BOOLEAN DEFAULT false,
  is_actioned BOOLEAN DEFAULT false,
  actioned_at TIMESTAMP WITH TIME ZONE,
  expires_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Recurring transactions/rules for prediction
CREATE TABLE public.recurring_patterns (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  pattern_type TEXT NOT NULL, -- 'income', 'expense', 'transfer'
  description TEXT NOT NULL,
  merchant_pattern TEXT, -- Regex or exact match for merchant
  amount_min DECIMAL(15,2),
  amount_max DECIMAL(15,2),
  typical_amount DECIMAL(15,2),
  frequency TEXT NOT NULL, -- 'daily', 'weekly', 'biweekly', 'monthly', 'quarterly', 'annually'
  day_of_month INTEGER, -- 1-31 for monthly
  day_of_week INTEGER, -- 0-6 for weekly
  category TEXT,
  is_essential BOOLEAN DEFAULT false, -- Fixed costs vs discretionary
  confidence_score DECIMAL(5,2),
  last_occurrence DATE,
  next_expected DATE,
  is_active BOOLEAN DEFAULT true,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS on all tables
ALTER TABLE public.bank_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bank_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transaction_reconciliations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tax_configurations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_tax_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recurring_patterns ENABLE ROW LEVEL SECURITY;

-- RLS Policies for bank_accounts
CREATE POLICY "Users can view their own bank accounts"
  ON public.bank_accounts FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own bank accounts"
  ON public.bank_accounts FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own bank accounts"
  ON public.bank_accounts FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own bank accounts"
  ON public.bank_accounts FOR DELETE
  USING (auth.uid() = user_id);

-- RLS Policies for bank_transactions
CREATE POLICY "Users can view their own bank transactions"
  ON public.bank_transactions FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own bank transactions"
  ON public.bank_transactions FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own bank transactions"
  ON public.bank_transactions FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own bank transactions"
  ON public.bank_transactions FOR DELETE
  USING (auth.uid() = user_id);

-- RLS Policies for transaction_reconciliations
CREATE POLICY "Users can view their own reconciliations"
  ON public.transaction_reconciliations FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own reconciliations"
  ON public.transaction_reconciliations FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own reconciliations"
  ON public.transaction_reconciliations FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own reconciliations"
  ON public.transaction_reconciliations FOR DELETE
  USING (auth.uid() = user_id);

-- Tax configurations are public read (global reference data)
CREATE POLICY "Anyone can view tax configurations"
  ON public.tax_configurations FOR SELECT
  USING (true);

-- RLS Policies for user_tax_settings
CREATE POLICY "Users can view their own tax settings"
  ON public.user_tax_settings FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own tax settings"
  ON public.user_tax_settings FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own tax settings"
  ON public.user_tax_settings FOR UPDATE
  USING (auth.uid() = user_id);

-- RLS Policies for financial_insights
CREATE POLICY "Users can view their own financial insights"
  ON public.financial_insights FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own financial insights"
  ON public.financial_insights FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own financial insights"
  ON public.financial_insights FOR UPDATE
  USING (auth.uid() = user_id);

-- RLS Policies for recurring_patterns
CREATE POLICY "Users can view their own recurring patterns"
  ON public.recurring_patterns FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own recurring patterns"
  ON public.recurring_patterns FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own recurring patterns"
  ON public.recurring_patterns FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own recurring patterns"
  ON public.recurring_patterns FOR DELETE
  USING (auth.uid() = user_id);

-- Create indexes for performance
CREATE INDEX idx_bank_accounts_user_id ON public.bank_accounts(user_id);
CREATE INDEX idx_bank_transactions_user_id ON public.bank_transactions(user_id);
CREATE INDEX idx_bank_transactions_account_id ON public.bank_transactions(bank_account_id);
CREATE INDEX idx_bank_transactions_date ON public.bank_transactions(transaction_date);
CREATE INDEX idx_reconciliations_user_id ON public.transaction_reconciliations(user_id);
CREATE INDEX idx_reconciliations_status ON public.transaction_reconciliations(match_status);
CREATE INDEX idx_tax_configs_country ON public.tax_configurations(country_code);
CREATE INDEX idx_financial_insights_user_id ON public.financial_insights(user_id);
CREATE INDEX idx_financial_insights_type ON public.financial_insights(insight_type);
CREATE INDEX idx_recurring_patterns_user_id ON public.recurring_patterns(user_id);

-- Insert initial tax configurations for major regions
INSERT INTO public.tax_configurations (country_code, country_name, tax_type, tax_name, standard_rate, threshold_amount, threshold_currency, filing_frequency, tax_year_start, effective_from, rules) VALUES
-- Australia
('AU', 'Australia', 'gst', 'GST', 10.00, 75000, 'AUD', 'quarterly', 'jul', '2000-07-01', '{"exemptions": ["basic food", "healthcare", "education"], "reduced_rates": []}'),
-- United Kingdom
('GB', 'United Kingdom', 'vat', 'VAT', 20.00, 85000, 'GBP', 'quarterly', 'apr', '2024-01-01', '{"reduced_rates": [{"rate": 5, "categories": ["home energy", "childrens car seats"]}, {"rate": 0, "categories": ["food", "books", "childrens clothing"]}]}'),
-- United States (no federal sales tax, placeholder)
('US', 'United States', 'sales_tax', 'Sales Tax', 0.00, NULL, 'USD', 'quarterly', 'jan', '2024-01-01', '{"note": "Sales tax varies by state", "state_rates": {}}'),
-- European Union - Germany
('DE', 'Germany', 'vat', 'USt/MwSt', 19.00, 22000, 'EUR', 'monthly', 'jan', '2024-01-01', '{"reduced_rates": [{"rate": 7, "categories": ["food", "books", "public transport"]}]}'),
-- New Zealand
('NZ', 'New Zealand', 'gst', 'GST', 15.00, 60000, 'NZD', 'bimonthly', 'apr', '2024-01-01', '{"exemptions": ["financial services", "residential rent"]}'),
-- Canada
('CA', 'Canada', 'gst', 'GST/HST', 5.00, 30000, 'CAD', 'quarterly', 'jan', '2024-01-01', '{"note": "Provincial sales tax may also apply", "hst_provinces": ["ON", "NB", "NS", "NL", "PE"]}'),
-- Singapore
('SG', 'Singapore', 'gst', 'GST', 9.00, 1000000, 'SGD', 'quarterly', 'jan', '2024-01-01', '{"exemptions": ["financial services", "residential property"]}'),
-- India
('IN', 'India', 'gst', 'GST', 18.00, 4000000, 'INR', 'monthly', 'apr', '2024-01-01', '{"slabs": [0, 5, 12, 18, 28], "composition_threshold": 15000000}'),
-- Ireland
('IE', 'Ireland', 'vat', 'VAT', 23.00, 37500, 'EUR', 'bimonthly', 'jan', '2024-01-01', '{"reduced_rates": [{"rate": 13.5, "categories": ["tourism", "construction"]}, {"rate": 9, "categories": ["newspapers", "sports facilities"]}]}'),
-- France
('FR', 'France', 'vat', 'TVA', 20.00, 34400, 'EUR', 'monthly', 'jan', '2024-01-01', '{"reduced_rates": [{"rate": 10, "categories": ["restaurants", "transport"]}, {"rate": 5.5, "categories": ["food", "books"]}, {"rate": 2.1, "categories": ["newspapers", "medicine"]}]}');

-- Create updated_at trigger function if not exists
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Add updated_at triggers
CREATE TRIGGER set_bank_accounts_updated_at
  BEFORE UPDATE ON public.bank_accounts
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_bank_transactions_updated_at
  BEFORE UPDATE ON public.bank_transactions
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_reconciliations_updated_at
  BEFORE UPDATE ON public.transaction_reconciliations
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_tax_configurations_updated_at
  BEFORE UPDATE ON public.tax_configurations
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_user_tax_settings_updated_at
  BEFORE UPDATE ON public.user_tax_settings
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_recurring_patterns_updated_at
  BEFORE UPDATE ON public.recurring_patterns
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();